// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2NwBdT1XB9-d6cK-0WzIiBxDDDlxMu1s',
    appId: '1:423659749763:web:bdc13be10cf601005a36b6',
    messagingSenderId: '423659749763',
    projectId: 'beco-login',
    authDomain: 'beco-login.firebaseapp.com',
    databaseURL: 'https://beco-login-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beco-login.appspot.com',
    measurementId: 'G-V0B2FFQTT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJDr5xpShLE_Bju21DEY2PZDPiY26Mh4',
    appId: '1:423659749763:android:b0a8ebb784bf6a465a36b6',
    messagingSenderId: '423659749763',
    projectId: 'beco-login',
    databaseURL: 'https://beco-login-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beco-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6rT6yCQWj-a_eweGNR79mhEMiVjl3wd8',
    appId: '1:423659749763:ios:b6c5280f4a338a795a36b6',
    messagingSenderId: '423659749763',
    projectId: 'beco-login',
    databaseURL: 'https://beco-login-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beco-login.appspot.com',
    iosClientId: '423659749763-1c42hhovkdc9vd2539sr5t9b7nb4ouqg.apps.googleusercontent.com',
    iosBundleId: 'com.beco.app',
  );
}
